<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class RiwayatTableSeeder extends Seeder
{
    public function run()
    {
        $riwayats = [
            // [
            //     'id_pelanggan' => 1,
            //     'reference' => Str::uuid(),
            //     'waktu_transaksi' => '2024-01-27',
            //     'total_bayar' => 128000,
            //     'jenis_pembayaran' => 'DANA',
            //     'nama_jenis_voucher' => 'Voucher A',
            //     'qty' => 32,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id_pelanggan' => 2,
            //     'reference' => Str::uuid(),
            //     'waktu_transaksi' => '2024-01-30',
            //     'total_bayar' => 265000,
            //     'jenis_pembayaran' => 'OVO',
            //     'nama_jenis_voucher' => 'Voucher B',
            //     'qty' => 55,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'id_pelanggan' => 3120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-20',
                'total_bayar' => 64000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '5000_24JAM',
                'qty' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 4120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-10',
                'total_bayar' => 21000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '5000_24JAM',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 5120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-05',
                'total_bayar' => 25000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '5000_24JAM',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 6120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-15',
                'total_bayar' => 50000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '5000_24JAM',
                'qty' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 7120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-25',
                'total_bayar' => 75000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 8120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-12',
                'total_bayar' => 100000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 9120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-22',
                'total_bayar' => 125000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 10120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-18',
                'total_bayar' => 150000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 11120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-28',
                'total_bayar' => 175000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 12120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-08',
                'total_bayar' => 200000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 13120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-02',
                'total_bayar' => 225000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 14120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-03',
                'total_bayar' => 250000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 15120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-04',
                'total_bayar' => 275000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '3000_10JAM',
                'qty' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 16120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-06',
                'total_bayar' => 300000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '1000_2JAM',
                'qty' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 17120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-07',
                'total_bayar' => 325000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '1000_2JAM',
                'qty' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 18120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-09',
                'total_bayar' => 350000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '1000_2JAM',
                'qty' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 19120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-11',
                'total_bayar' => 375000,
                'jenis_pembayaran' => 'DANA',
                'nama_jenis_voucher' => '1000_2JAM',
                'qty' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pelanggan' => 20120624,
                'reference' => Str::uuid(),
                'waktu_transaksi' => '2024-01-13',
                'total_bayar' => 400000,
                'jenis_pembayaran' => 'OVO',
                'nama_jenis_voucher' => '1000_2JAM',
                'qty' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($riwayats as $riwayat) {
            DB::table('riwayat')->insert($riwayat);
        }
    }
}
